[package]
name = "riven_cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "riven_cli"
path = "src/lib.rs"

[[bin]]
name = "riven"
path = "src/main.rs"

[features]
llvm = ["riven_core/llvm"]

[dependencies]
riven_core = { path = "../../compiler/riven_core" }
clap = { version = "4", features = ["derive"] }
toml = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
ar = "0.9"

[dev-dependencies]
riven_core = { path = "../../compiler/riven_core" }
tempfile = "3"

[lints]
workspace = true
