[workspace]
members = ["compiler/*", "src/*"]
resolver = "2"

[workspace.package]
rust-version = "1.91"
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/sherazp995/riven"

[workspace.lints.clippy]
result_large_err = "allow"
large_enum_variant = "allow"
module_inception = "allow"
too_many_arguments = "allow"
should_implement_trait = "allow"
only_used_in_recursion = "allow"
