//! Filesystem, path, primitive-conversion, and String runtime symbols.

// std::fs + std::path surface, plus File / OpenOptions.
pub(in crate::codegen::runtime) const FS_PATH: &[&str] = &[
    "riven_fs_is_file",
    "riven_fs_is_dir",
    "riven_fs_read_dir",
    // Phase 2 stdlib (#06): fs::metadata + Metadata accessor surface.
    "riven_fs_metadata",
    "riven_metadata_len",
    "riven_metadata_modified",
    "riven_metadata_is_file",
    "riven_metadata_is_dir",
    "riven_metadata_is_symlink",
    "riven_metadata_free",
    // Phase 2 stdlib (#06.5 T2): std::io::File + OpenOptions builder.
    "riven_file_open",
    "riven_file_create",
    "riven_file_append",
    "riven_file_open_options",
    "riven_file_read",
    "riven_file_read_to_string",
    "riven_file_read_all",
    "riven_file_write",
    "riven_file_write_all",
    "riven_file_write_str",
    "riven_file_flush",
    "riven_file_seek",
    "riven_file_metadata",
    "riven_file_close",
    "riven_file_drop",
    "riven_open_options_new",
    "riven_open_options_read",
    "riven_open_options_write",
    "riven_open_options_append",
    "riven_open_options_truncate",
    "riven_open_options_create",
    "riven_open_options_create_new",
    "riven_fs_read_to_string",
    "riven_fs_write",
    "riven_fs_exists",
    "riven_fs_remove_file",
    "riven_fs_create_dir",
    "riven_fs_create_dir_all",
    "riven_fs_rename",
    // Phase 2 stdlib (#06.5 T3): fs completeness.
    "riven_fs_copy",
    "riven_fs_remove_dir_all",
    "riven_fs_canonicalize",
    "riven_fs_write_atomic",
    "riven_fs_read_link",
    "riven_fs_symlink",
    // std::path (Phase 3): Unix-style path manipulation. Empty-string
    // sentinel for parent/file_name/extension when no value applies.
    "riven_path_join",
    "riven_path_parent",
    "riven_path_file_name",
    "riven_path_extension",
    "riven_path_is_absolute",
];

// Primitive conversion helpers (int/float/bool/char → String, etc).
pub(in crate::codegen::runtime) const PRIMITIVES: &[&str] = &[
    "riven_print_int",
    "riven_print_float",
    "riven_int_to_string",
    "riven_float_to_string",
    "riven_bool_to_string",
    "riven_char_to_string",
];

// String stdlib surface.
pub(in crate::codegen::runtime) const STRING: &[&str] = &[
    "riven_string_concat",
    "riven_string_from",
    "riven_string_to_upper",
    "riven_string_chars",
    "riven_string_eq",
    "riven_string_cmp",
    "riven_string_hash",
    "riven_string_contains",
    "riven_string_starts_with",
    "riven_string_ends_with",
    "riven_string_repeat",
    "riven_string_lines",
    "riven_string_replace",
    // String stdlib methods (#02 Phase 2 stdlib).
    "riven_string_new",
    "riven_string_with_capacity",
    "riven_string_as_str",
    "riven_string_to_string",
    "riven_string_bytes",
    "riven_string_trim_start",
    "riven_string_trim_end",
    "riven_string_find",
    "riven_string_splitn",
    "riven_string_clear",
    "riven_string_truncate",
    "riven_string_insert",
    "riven_string_insert_str",
    "riven_string_remove",
    "riven_string_parse_int",
    "riven_string_parse_float",
    "riven_parse_error_message",
    // String stdlib batch 2 (#02): split / push / into_bytes.
    "riven_string_split",
    "riven_string_push",
    "riven_string_into_bytes",
    "riven_string_from_iter",
];
